AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

# amd: these seem extreme
Lint/AssignmentInCondition: { Enabled: false }
Lint/SuppressedException: { Enabled: false }
Metrics: { Enabled: false }
Naming/BinaryOperatorParameterName: { Enabled: false }
Naming/HeredocDelimiterNaming: { Enabled: false }
Naming/MethodParameterName: { Enabled: false }
Style/AccessorGrouping: { Enabled: false }
Style/AsciiComments: { Enabled: false }
Style/ClassAndModuleChildren: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DoubleNegation: { Enabled: false }
Style/FormatStringToken: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/GuardClause: { Enabled: false }
Style/HashTransformValues: { Enabled: false }
Style/IfUnlessModifier: { Enabled: false }
Style/NegatedIf: { Enabled: false }
Style/Next: { Enabled: false }
Style/NumericPredicate: { Enabled: false }
Style/ParallelAssignment: { Enabled: false }
Style/PerlBackrefs: { Enabled: false }
Style/RaiseArgs: { Enabled: false }
Style/RedundantAssignment: { Enabled: false }
Style/RegexpLiteral: { Enabled: false }
Style/SoleNestedConditional: { Enabled: false }
Style/StderrPuts: { Enabled: false }
