require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

#
# fight with standardrb!
#

Style/RedundantReturn: { Enabled: false }
Style/HashSyntax: { EnforcedShorthandSyntax: always }
